# Generated by Django 5.1 on 2024-08-20 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landtitles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
    ]
