# Generated by Django 5.1 on 2024-09-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landtitles', '0002_remove_profile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(max_length=15),
        ),
    ]
