# Generated by Django 5.1 on 2024-09-05 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landtitles', '0003_alter_profile_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address',
            new_name='cniId',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='birth_location',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='dob',
            new_name='profession',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='surname',
            new_name='username',
        ),
    ]
