# Generated by Django 5.1 on 2024-09-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landtitles', '0004_rename_address_profile_cniid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
