# Generated by Django 5.1 on 2024-09-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landtitles', '0005_userlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
