# Generated by Django 5.1 on 2024-09-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landtitles', '0009_landtitle_transferownership'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='landtitle',
            name='coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landtitle',
            name='surface_area',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
