# Generated by Django 5.1 on 2024-09-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landtitles', '0010_fileupload_delete_message_delete_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landtitle',
            name='id',
        ),
        migrations.AlterField(
            model_name='landtitle',
            name='land_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
