# Generated by Django 5.1 on 2024-09-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landtitles', '0013_pdffile_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='landtitle',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='landtitle',
            name='delivery_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='landtitle',
            name='dob',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='landtitle',
            name='father_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='landtitle',
            name='mother_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='landtitle',
            name='nature',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='landtitle',
            name='pob',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='landtitle',
            name='profession',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
