# Generated by Django 5.1 on 2024-09-30 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landtitles', '0014_landtitle_address_landtitle_delivery_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotarialDeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notary_name', models.CharField(max_length=255)),
                ('seller_name', models.CharField(max_length=255)),
                ('land_size', models.CharField(max_length=100)),
                ('land_location', models.CharField(max_length=255)),
                ('buyer_name', models.CharField(max_length=255)),
                ('land_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('present_date', models.DateField()),
            ],
        ),
    ]
