# Generated by Django 5.1 on 2024-09-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landtitles', '0015_notarialdeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='notarialdeed',
            name='notarial_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notarialdeed',
            name='buyer_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notarialdeed',
            name='land_location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notarialdeed',
            name='land_price',
            field=models.DecimalField(decimal_places=22, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='notarialdeed',
            name='land_size',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notarialdeed',
            name='notary_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notarialdeed',
            name='seller_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
