# Generated by Django 5.1 on 2024-10-03 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landtitles', '0016_notarialdeed_notarial_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
    ]
