# Generated by Django 5.1 on 2024-10-03 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landtitles', '0017_emailmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailMessage',
        ),
    ]
