# Generated by Django 5.1 on 2024-10-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landtitles', '0018_delete_emailmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('file', models.FileField(upload_to='attachments/')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
