# Generated by Django 5.1 on 2024-10-12 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landtitles', '0021_appointment_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='code',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
    ]
